# Generated by Django 3.2.7 on 2021-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stlFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stlfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
