# Generated by Django 3.2.7 on 2021-09-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stlViwerApp', '0004_alter_filemodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='title',
        ),
    ]
